### ISSUE TITLE
Build a calculator using only static and class methods.

### ISSUE THREAD

**Issue by daviddigital** [rmotr-curriculum/advanced-python-programming-questions#18]
**User code**:
```python
class Calculator(object):
    
    def add(self, x, y):
        return x + y     
    def subtract(self, x, y):
        return x-y 
    def multiply(self, x, y):
        return x * y  
    def divide(self, x, y):
        return x / y
        
calc = Calculator()
print(calc.add(2,2))
print(calc.subtract(4,2))
```

**Comment by adriverhagen** [comment]
@daviddigital  perhaps this resource could help : https://stackoverflow.com/questions/136097/what-is-the-difference-between-staticmethod-and-classmethod-in-python

**Comment by santiagobasulto** [comment]
@daviddigital the difference between `staticmethod` and `classmethod` is only that, a `classmethod` will receive as first parameter the class involved in the call. It's silly and simple, but it's the only difference. Remember, we usually recommend to use `classmethod`s over `staticmethod`s.
