### ISSUE TITLE
Kilograms/pounds

### ISSUE THREAD

**Issue by etownbetty** [rmotr-curriculum/advanced-python-programming-questions#19]
How can you have pounds OR kilograms initialized, but not both? I just don't get the syntax. (don't look at the rest of the code, I'm just starting this problem)

**Assignment**: http://learn.rmotr.com/python/advanced-python-programming/advanced-oop-iterators/weight-operations

**User code**:
```python
class Weight(object):
    
    def __init__(self, kilograms, pounds):
        self.pounds = pounds
        self.kilograms = kilograms
        
    def pounds(self, other):
        
        return Weight(self.pounds + other.pounds)
        
    def kilograms(self):
        
        return Weight(self.kilograms + other.kilograms)
        
```

**Comment by palpen** [comment]
Hi @etownbetty. I found this solution which seems to work

    class Weight(object):
        def __init__(self, **kwargs):
            if len(kwargs) > 1:
                raise Exception("Too many arguments. Must either be pounds or kilograms") 
            self.__dict__.update(kwargs)

`kwargs` stands for keyword arguments. This allows you to initiate the following classes with an arbitrary number of attributes. To see this, run the following:

    wt_lbs = Weight(pounds=2.205)
    wt_kg = Weight(kilograms=1)
    wt_lbs_kg = Weight(pounds=2.205, kilograms=1)

    print(vars(wt_lbs))
    print(vars(wt_kg))
    print(vars(wt_lbs_kg))

The idea behind it is that `self.__dict__` returns a dictionary containing all the attributes of `self`, which you have provided when you initialized the `Weight` class. The `update()` method then updates this dictionary with the contents of the `kwargs`, which itself is a dictionary containing the key-value you have provided when you initialized the class. I think this is how it works---somebody please comment if I made a mistake.

**Comment by santiagobasulto** [comment]
Great question @etownbetty . A simple solution for this is to make them both optional: `def __init__(self, kilograms=None, pounds=None):`, but check for at least 1 value in side the method:

```
class Weight(object):
    def __init__(self, kilograms=None, pounds=None):
        if not any([kilograms, pounds]):
            raise ValueError("At least one value must be passed").
        self.pounds = pounds
        self.kilograms = kilograms
```

I think @palpen is more accurate in this case though, so also check that answer!
