### ISSUE TITLE
Input clarification

### ISSUE THREAD

**Issue by AllenAnthes** [rmotr-curriculum/advanced-python-programming-questions#20]
Can we assume that the duplicates will always be adjacent in the input list?

Edit - I know I'm probably overthinking the assignment.  My thought process is that using "in list" is (I believe) an O(n) operation on lists, which could be reduced to constant time if the adjacency was guaranteed.  

**Assignment**: http://learn.rmotr.com/python/advanced-python-programming/functional-programming/remove-duplicates-in-order

**User code**:
```python
def remove_duplicates_in_order(a_list):
    new_list = []
    for item in a_list:
        if item not in new_list:
            new_list.append(item)

    return new_list
```

**Comment by santiagobasulto** [comment]
The code is exactly right! There's no other way to do O(n) for this particular operation, as you must check EVERY possible element. The operation `item in new_list` is expensive for lists, so, in a situation with more elements it **might** make sense to keep a separate set (or similar data structure) to perform the `item in new_list` operation. A good idea might be a [bloom filter](https://en.wikipedia.org/wiki/Bloom_filter). This is a clear example of the tradeoff between computation efficiency and storage efficiency (CPU vs Memory).
